---
apiVersion: v1
kind: Service
metadata:
  name: router-lan
  namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: router-lan
  namespace: default
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - name: http
        port: 80
