---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/sonarr
              tag: latest
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              GUID: "1000"

    service:
      main:
        ports:
          http:
            port: 8989

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: sonarr.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: sonarr
                  port: 8989

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: sonarr-tls
            hosts:
              - sonarr.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: app-configs-pvc
        advancedMounts:
          main:
            main:
              - path: /config
                subPath: sonarr

      downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: downloads
        globalMounts:
          - path: /downloads

      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        advancedMounts:
          main:
            main:
              - path: /tv
                subPath: tv
