---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lan-gateway
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: nginxinc/nginx-unprivileged
              tag: "1.29.2-alpine"
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 150m
                memory: 128Mi

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: nas.khzaw.dev,router.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: nas.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
          - host: router.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: lan-gateway-tls
            hosts:
              - nas.khzaw.dev
              - router.khzaw.dev

    configMaps:
      config:
        enabled: true
        data:
          default.conf: |
            server {
              listen 8080 default_server;
              server_name _;
              return 404;
            }

            server {
              listen 8080;
              server_name nas.khzaw.dev;

              location / {
                proxy_pass https://10.0.0.210;
                proxy_http_version 1.1;
                proxy_set_header Host nas.khzaw.dev;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto https;
                proxy_read_timeout 3600;
                proxy_send_timeout 3600;
                proxy_ssl_server_name off;
                proxy_ssl_verify off;
              }
            }

            server {
              listen 8080;
              server_name router.khzaw.dev;

              location / {
                proxy_pass https://10.0.0.1;
                proxy_http_version 1.1;
                proxy_set_header Host 10.0.0.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto https;
                proxy_read_timeout 3600;
                proxy_send_timeout 3600;
                proxy_ssl_server_name off;
                proxy_ssl_verify off;
                proxy_redirect ~^https?://10\.0\.0\.1(/.*)?$ https://router.khzaw.dev$1;
              }
            }

    persistence:
      config:
        enabled: true
        type: configMap
        identifier: config
        advancedMounts:
          main:
            main:
              - path: /etc/nginx/conf.d/default.conf
                subPath: default.conf
                readOnly: true
