# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/infra.contrib.fluxcd.io/terraform_v1alpha2.json
---
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: cloudflare-dns
  namespace: flux-system
spec:
  interval: 5m
  approvePlan: auto
  path: ./infrastructure/terraform/cloudflare-dns
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  # varsFrom:
  #   - kind: Secret
  #     name: cloudflare-api-token
  #     varsKeys:
  #       - cloudflare-api-token
  vars:
    - name: cloudflare_zone_id
      value: "06575a5b0478672278b2a86a5b145d9a"
    - name: domain_name
      value: "khzaw.dev"
    - name: metallb_ip
      value: "10.0.0.230"

  runnerPodTemplate:
    spec:
      env:
        - name: CLOUDFLARE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-token
              key: token
