apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:8lcDJff5BX+qp/IwkIwc897yOfUhR64l0KqPaxqI2A6gNJgmWvTMwFqGiF1NcElGe1nbulhXbL27pWeJfp/Hm0I+3yjhPnysWF8vbOLapxlOIOZw2x5v7dJAMfzpMlaXQywjswralGnO4dq7vZPUG/CYE6HilUs2IsOPMnPLBWBRaSLstaFZ00uct6bkvEBAOgPR+AdGIi2uc5tweDtjVCBl0DCzfDGsiXKE81qVWsLpD+beamebtE1KRxt9lYdUC6c+ShjgC5fLXIkztBsjTaiUek/CrCB/zIdNb8pY97AIlRJT,iv:+RP+HKnYFsWu5D+pkWtfgn+UPkHwqTPTUcW2zgF1sDE=,tag:d4txNwhonBIZ/jNZrwZxcw==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMW9RaXhKSEhyNERMOFls
            YkgwZm9rUThuQjJKNCtVWTBiK3JmWmRNUmxZCnpsYnZ3V2I5SmsyT1B0dWtFeVg1
            eHBUL1hvUWRURFI1eFZMcEFkY2VMUjAKLS0tIEtTcG9xblF6WHAvRTBBVVlJSExI
            OXZMWEE2cFJMYmRpMWpXYjRyWkRCWU0KIp+URZrsZaRSBODsB9HoE465TR//eojx
            29CsWKuKreIyNdef+6j04xhc8xiBCXncknNNP7iIQZYdqJ3lkqag7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:37:22Z"
    mac: ENC[AES256_GCM,data:YsgKEv/vAhISc4RUJcR4LGaZ8n1LYpuSkKxnSvwrHdEynPjosx5qAWQhyl7T/Rr4184i4IYuRuvwt3z6pHO7+a0IXlvef5M6YBUnnFjuTwt4U8xP2HXL3HvXqjRxLu679plxNsOrPg8v8vcv6qCAD118haHX2LzVqdnPM872JM4=,iv:o5PFLGOjRCVmlW17leKOYyXTwV7v3yaO7kWEninXt0M=,tag:6EgEJzv1egpV8jT21ScT6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
