---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: homepage
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: homepage-charts
        namespace: flux-system
      interval: 5m
  install: { remediation: { retries: 3 } }
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.10.1

    env:
      - name: TZ
        value: Asia/Singapore
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: hq.khzaw.dev,localhost,127.0.0.1

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: hq.khzaw.dev, home.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: hq.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - hq.khzaw.dev

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

    config:
      bookmarks: []
      kubernetes:
        mode: disable
      settings:
        title: KHZ HQ
        description: Rangoonpulse Homelab
        theme: dark
        color: zinc
        iconStyle: theme
        headerStyle: boxedWidgets
        statusStyle: dot
        fullWidth: true
        useEqualHeights: true
        hideVersion: true
        target: _self
        quicklaunch:
          provider: duckduckgo
          searchDescriptions: true
          showSearchSuggestions: true
        layout:
          Watch & Listen:
            style: row
            columns: 4
          Acquisition:
            style: row
            columns: 7
          Books:
            style: row
            columns: 3
          Ops:
            style: row
            columns: 6
      services:
        - Apps:
            - Actual Budget:
                icon: mdi-currency-usd
                href: https://actual.khzaw.dev
                description: Personal finance
            - Jellyfin:
                icon: mdi-movie-open
                href: https://jellyfin.khzaw.dev
                description: Media streaming
            - Immich:
                icon: mdi-image-multiple
                href: https://photos.khzaw.dev
                description: Photos management
            - Jellyseerr:
                icon: mdi-television-guide
                href: https://entertainment.khzaw.dev
                description: Media requests
        - Books:
            - Audiobookshelf:
                icon: mdi-book-music
                href: https://audiobookshelf.khzaw.dev
                description: Books and audiobooks
            - Calibre Web:
                icon: mdi-book-open-page-variant
                href: https://calibre.khzaw.dev
                description: Calibre
            - Calibre Manage:
                icon: mdi-book-edit-outline
                href: https://calibre-manage.khzaw.dev
                description: Calibre VNC
        - Arr Stack:
            - Sonarr:
                icon: mdi-television-classic
                href: https://sonarr.khzaw.dev
                description: Series manager
            - Radarr:
                icon: mdi-movie-roll
                href: https://radarr.khzaw.dev
                description: Movie manager
            - Tunarr:
                icon: mdi-television-play
                href: https://tunarr.khzaw.dev
                description: TV Channels scheduler
            - Prowlarr:
                icon: mdi-radar
                href: https://prowlarr.khzaw.dev
                description: Indexer manager
            - Bazarr:
                icon: mdi-subtitles
                href: https://bazarr.khzaw.dev
                description: Subtitles
            - Notifiarr:
                icon: mdi-bell-ring-outline
                href: https://notifiarr.khzaw.dev
                description: Trash guides sync
        - Downloaders:
            - Transmission:
                icon: mdi-arrow-down-circle
                href: https://torrent.khzaw.dev
                description: Torrent
            - SABnzbd:
                icon: mdi-download-network
                href: https://sabnzbd.khzaw.dev
                description: Usenet downloader
        - Ops:
            - Jellystat:
                icon: mdi-chart-box
                href: https://jellystat.khzaw.dev
                description: Jellyfin analytics
            - Grafana:
                icon: mdi-chart-box
                href: https://grafana.khzaw.dev
                description: Grafana
            - Uptime:
                icon: mdi-heart-pulse
                href: https://uptime-kuma.khzaw.dev
                description: Uptime checks
            - Router:
                icon: mdi-router-network
                href: http://10.0.0.1
                description: Router
            - NAS:
                icon: mdi-nas
                href: http://10.0.0.210
                description: TrueNAS Scale
      widgets:
        - search:
            provider: google
            target: _blank
            showSearchSuggestions: true
        - datetime:
            text_size: xl
            format:
              dateStyle: medium
              timeStyle: short
              hourCycle: h23
