---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: homepage
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: homepage-charts
        namespace: flux-system
      interval: 5m
  install: { remediation: { retries: 3 } }
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.10.1

    env:
      - name: TZ
        value: Asia/Singapore
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: hq.khzaw.dev,localhost,127.0.0.1
      # Requires secret `homepage-widget-secrets` in namespace `default`.
      - name: HOMEPAGE_VAR_IMMICH_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: IMMICH_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_SONARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: SONARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_RADARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: RADARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_JELLYSEERR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: JELLYSEERR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_PROWLARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: PROWLARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_JELLYSTAT_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: JELLYSTAT_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_BAZARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: BAZARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_SABNZBD_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: SABNZBD_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_JELLYFIN_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: JELLYFIN_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_FINNHUB_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: FINNHUB_API_KEY
            optional: true
      # - name: HOMEPAGE_VAR_SPEEDTEST_API_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: homepage-widget-secrets
      #       key: SPEEDTEST_API_KEY
      #       optional: true

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: hq.khzaw.dev, home.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: hq.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - hq.khzaw.dev

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

    config:
      bookmarks: []
      kubernetes:
        mode: disable
      settings:
        title: Rangoonpulse — HQ
        description: Rangoonpulse
        theme: dark
        color: zinc
        iconStyle: theme
        headerStyle: clean
        statusStyle: dot
        fullWidth: true
        useEqualHeights: false
        hideVersion: true
        target: _self
        providers:
          finnhub: "{{HOMEPAGE_VAR_FINNHUB_API_KEY}}"
        quicklaunch:
          provider: duckduckgo
          searchDescriptions: true
          showSearchSuggestions: true
        layout:
          Apps:
            style: row
            columns: 4
          Downloaders:
            style: row
            columns: 2
          Arr Stack:
            style: row
            columns: 4
          Books:
            style: row
            columns: 3
          Ops:
            style: row
            columns: 6
      services:
        - Apps:
            - Actual Budget:
                icon: actual-budget.png
                href: https://actual.khzaw.dev
                description: Personal finance
            - Vaultwarden:
                icon: vaultwarden.png
                href: https://passwords.khzaw.dev
                description: Password manager
            - Jellyfin:
                icon: jellyfin.png
                href: https://jellyfin.khzaw.dev
                description: Media streaming
                widget:
                  type: jellyfin
                  url: https://jellyfin.khzaw.dev
                  key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
                  version: 2
                  enableBlocks: 2
                  enableNowPlaying: true
                  enableUser: true
            - Immich:
                icon: immich.png
                href: https://photos.khzaw.dev
                description: Photos management
                widget:
                  type: immich
                  url: https://photos.khzaw.dev
                  key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
                  version: 2
        - Books:
            - Audiobookshelf:
                icon: audiobookshelf.png
                href: https://audiobookshelf.khzaw.dev
                description: Books and audiobooks
            - Calibre Web:
                icon: calibre.png
                href: https://calibre.khzaw.dev
                description: Calibre
            - Calibre Manage:
                icon: calibre.png
                href: https://calibre-manage.khzaw.dev
                description: Calibre VNC
        - Arr Stack:
            - Sonarr:
                icon: sonarr.png
                href: https://sonarr.khzaw.dev
                description: Series manager
                widget:
                  type: sonarr
                  url: https://sonarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
                  enableQueue: false
            - Radarr:
                icon: radarr.png
                href: https://radarr.khzaw.dev
                description: Movie manager
                widget:
                  type: radarr
                  url: https://radarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
                  enableQueue: false
            - Seerr:
                icon: jellyseerr.png
                href: https://entertainment.khzaw.dev
                description: Media requests
                widget:
                  type: jellyseerr
                  url: https://entertainment.khzaw.dev
                  key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"
                  fields:
                    - pending
                    - approved
                    - available
                    - issues
            - Prowlarr:
                icon: prowlarr.png
                href: https://prowlarr.khzaw.dev
                description: Indexer manager
                widget:
                  type: prowlarr
                  url: https://prowlarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
            - Bazarr:
                icon: bazarr.png
                href: https://bazarr.khzaw.dev
                description: Subtitles
                widget:
                  type: bazarr
                  url: https://bazarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
            - Tunarr:
                icon: tunarr.png
                href: https://tunarr.khzaw.dev
                description: TV Channels scheduler
            - Notifiarr:
                icon: notifiarr.png
                href: https://notifiarr.khzaw.dev
                description: Trash guides sync
        - Downloaders:
            - Transmission:
                icon: transmission.png
                href: https://torrent.khzaw.dev
                description: Torrent
                widget:
                  type: transmission
                  url: https://torrent.khzaw.dev
                  username: ""
                  password: ""
            - SABnzbd:
                icon: sabnzbd.png
                href: https://sabnzbd.khzaw.dev
                description: Usenet downloader
                widget:
                  type: sabnzbd
                  url: https://sabnzbd.khzaw.dev
                  key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
        - Ops:
            - Jellystat:
                icon: jellystat.png
                href: https://jellystat.khzaw.dev
                description: Jellyfin analytics
                widget:
                  type: jellystat
                  url: https://jellystat.khzaw.dev
                  key: "{{HOMEPAGE_VAR_JELLYSTAT_API_KEY}}"
                  days: 90
            - Uptime:
                icon: uptime-kuma.png
                href: https://uptime.khzaw.dev
                description: Uptime checks
                widget:
                  type: uptimekuma
                  url: http://uptime-kuma.default.svc.cluster.local:3001
                  slug: rangoonpulse
            - Glance:
                icon: glance.png
                href: https://glance.khzaw.dev
                description: Minimal dashboard
            - Grafana:
                icon: grafana.png
                href: https://grafana.khzaw.dev
                description: Grafana
            # - Speedtest:
            #     icon: speedtest.png
            #     href: https://speedtest.khzaw.dev
            #     description: Internet speed trend
            #     widget:
            #       type: speedtest
            #       url: https://speedtest.khzaw.dev
            #       key: "{{HOMEPAGE_VAR_SPEEDTEST_API_KEY}}"
            #       version: 2
            #       bitratePrecision: 1
            - Router:
                icon: router.png
                href: https://router.khzaw.dev
                description: Router
            - NAS:
                icon: truenas.png
                href: https://nas.khzaw.dev
                description: TrueNAS Scale
      widgets:
        - search:
            provider: google
            target: _blank
            showSearchSuggestions: true
        - datetime:
            text_size: lg
            format:
              dateStyle: medium
              timeStyle: short
              hourCycle: h23
        - stocks:
            provider: finnhub
            color: true
            cache: 1
            watchlist:
              - TQQQ
              - META
              - NET
              - AAPL
              - MSFT
              - GOOGL
              - AMZN
              - TSLA
