---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: homepage
      version: "2.1.0"
      sourceRef:
        kind: HelmRepository
        name: homepage-charts
        namespace: flux-system
      interval: 5m
  install: { remediation: { retries: 3 } }
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.10.1

    env:
      - name: TZ
        value: Asia/Singapore
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: hq.khzaw.dev,localhost,127.0.0.1
      - name: HOMEPAGE_VAR_SONARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: SONARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_RADARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: RADARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_JELLYSEERR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: JELLYSEERR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_PROWLARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: PROWLARR_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_JELLYSTAT_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: JELLYSTAT_API_KEY
            optional: true
      - name: HOMEPAGE_VAR_BAZARR_API_KEY
        valueFrom:
          secretKeyRef:
            name: homepage-widget-secrets
            key: BAZARR_API_KEY
            optional: true

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: hq.khzaw.dev, home.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: hq.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - hq.khzaw.dev

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

    config:
      bookmarks: []
      kubernetes:
        mode: disable
      settings:
        title: Rangoonpulse — HQ
        description: Rangoonpulse
        theme: dark
        color: zinc
        iconStyle: theme
        headerStyle: boxedWidgets
        statusStyle: dot
        fullWidth: true
        useEqualHeights: true
        hideVersion: true
        target: _self
        quicklaunch:
          provider: duckduckgo
          searchDescriptions: true
          showSearchSuggestions: true
        layout:
          Apps:
            style: row
            columns: 6
          Downloaders:
            style: row
            columns: 2
          Arr Stack:
            style: row
            columns: 8
          Books:
            style: row
            columns: 8
          Ops:
            style: row
            columns: 8
      services:
        - Apps:
            - Actual Budget:
                icon: actual-budget.png
                href: https://actual.khzaw.dev
                description: Personal finance
            - Jellyfin:
                icon: jellyfin.png
                href: https://jellyfin.khzaw.dev
                description: Media streaming
            - Immich:
                icon: immich.png
                href: https://photos.khzaw.dev
                description: Photos management
        - Books:
            - Audiobookshelf:
                icon: audiobookshelf.png
                href: https://audiobookshelf.khzaw.dev
                description: Books and audiobooks
            - Calibre Web:
                icon: calibre-web.png
                href: https://calibre.khzaw.dev
                description: Calibre
            - Calibre Manage:
                icon: calibre.png
                href: https://calibre-manage.khzaw.dev
                description: Calibre VNC
        - Arr Stack:
            - Sonarr:
                icon: sonarr.png
                href: https://sonarr.khzaw.dev
                description: Series manager
                widget:
                  type: sonarr
                  url: https://sonarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_SONARR_API_KEY}}"
                  enableQueue: false
            - Radarr:
                icon: radarr.png
                href: https://radarr.khzaw.dev
                description: Movie manager
                widget:
                  type: radarr
                  url: https://radarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
                  enableQueue: false
            - Seerr:
                icon: jellyseerr.png
                href: https://entertainment.khzaw.dev
                description: Media requests
                widget:
                  type: jellyseerr
                  url: https://entertainment.khzaw.dev
                  key: "{{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}"
                  fields:
                    - pending
                    - approved
                    - available
                    - issues
            - Tunarr:
                icon: tunarr.png
                href: https://tunarr.khzaw.dev
                description: TV Channels scheduler
            - Prowlarr:
                icon: prowlarr.png
                href: https://prowlarr.khzaw.dev
                description: Indexer manager
                widget:
                  type: prowlarr
                  url: https://prowlarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_PROWLARR_API_KEY}}"
            - Bazarr:
                icon: bazarr.png
                href: https://bazarr.khzaw.dev
                description: Subtitles
                widget:
                  type: bazarr
                  url: https://bazarr.khzaw.dev
                  key: "{{HOMEPAGE_VAR_BAZARR_API_KEY}}"
            - Notifiarr:
                icon: notifiarr.png
                href: https://notifiarr.khzaw.dev
                description: Trash guides sync
        - Downloaders:
            - Transmission:
                icon: transmission.png
                href: https://torrent.khzaw.dev
                description: Torrent
            - SABnzbd:
                icon: sabnzbd.png
                href: https://sabnzbd.khzaw.dev
                description: Usenet downloader
        - Ops:
            - Glance:
                icon: glance.png
                href: https://glance.khzaw.dev
                description: Minimal dashboard
            - Vaultwarden:
                icon: vaultwarden.png
                href: https://passwords.khzaw.dev
                description: Password manager
            - Jellystat:
                icon: jellystat.png
                href: https://jellystat.khzaw.dev
                description: Jellyfin analytics
                widget:
                  type: jellystat
                  url: https://jellystat.khzaw.dev
                  key: "{{HOMEPAGE_VAR_JELLYSTAT_API_KEY}}"
                  days: 30
            - Grafana:
                icon: grafana.png
                href: https://grafana.khzaw.dev
                description: Grafana
            - Uptime:
                icon: uptime-kuma.png
                href: https://uptime-kuma.khzaw.dev
                description: Uptime checks
                widget:
                  type: uptimekuma
                  url: http://uptime-kuma.default.svc.cluster.local:3001
                  slug: rangoonpulse
            - Router:
                icon: router.png
                href: http://10.0.0.1
                description: Router
            - NAS:
                icon: truenas.png
                href: http://10.0.0.210
                description: TrueNAS Scale
      widgets:
        - search:
            provider: google
            target: _blank
            showSearchSuggestions: true
        - datetime:
            text_size: xl
            format:
              dateStyle: medium
              timeStyle: short
              hourCycle: h23
