# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: santiagosayshey/profilarr
              tag: latest
            env:
              TZ: "Asia/Singapore"
            resources:
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"

    service:
      main:
        controller: main
        ports:
          http:
            port: 6868

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: profilarr.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/hostname: profilarr.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: profilarr-tls
            hosts:
              - profilarr.khzaw.dev

    persistence:
      # Profilarr stores its state (including its internal DB) under /config.
      # This uses local-path because SQLite-style DB files can be unreliable on NFS mounts.
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config

