# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.6.2"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: ${PRIMARY_NODE_NAME}

    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: vaultwarden/server
              tag: "1.35.8"
            env:
              TZ: "${TIMEZONE}"
              DOMAIN: "https://passwords.${BASE_DOMAIN}"
              SIGNUPS_ALLOWED: "true"
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden-db-secret
                    key: DATABASE_URL
              DATABASE_MAX_CONNS: "20"
              DATABASE_TIMEOUT: "30"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "600m"
                memory: "1Gi"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: passwords.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
          - host: password.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

        annotations:
          external-dns.alpha.kubernetes.io/hostname: passwords.${BASE_DOMAIN}
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "128m"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: vaultwarden-tls
            hosts:
              - passwords.${BASE_DOMAIN}
              - password.${BASE_DOMAIN}

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: vaultwarden-data-local
        globalMounts:
          - path: /data
