# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/service-v1.json
---
apiVersion: v1
kind: Service
metadata:
  name: password-cname
  namespace: default
  annotations:
    # Create `password.khzaw.dev` as a DNS alias to `passwords.khzaw.dev`.
    # external-dns must watch Services (`--source=service`) for this to work.
    external-dns.alpha.kubernetes.io/hostname: password.khzaw.dev
spec:
  type: ExternalName
  externalName: passwords.khzaw.dev

