apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: {remediation: {retries: 3}}
  upgrade: {remediation: {retries: 3}}
  values:
    controllers:
      main:
        replicas: 1
        pod:
          nodeSelector:
            kubernetes.io/hostname: talos-7nf-osf
        containers:
          main:
            image:
              repository: ghcr.io/khzaw/blog
              tag: 1771772272-d50dc4187eb92a2c810aaa77f2f47a6cd8b3fb48 # {"$imagepolicy": "flux-system:blog:tag"}
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  periodSeconds: 10
            resources:
              requests:
                cpu: "12m"
                memory: "20Mi"
              limits:
                cpu: "100m"
                memory: "40Mi"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: blog.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: blog-tls
            hosts:
              - blog.khzaw.dev
