apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-custom-headers
  namespace: ingress-nginx
data:
  X-Content-Type-Options: "nosniff"
  X-Frame-Options: "SAMEORIGIN"
  Referrer-Policy: "strict-origin-when-cross-origin"
  X-XSS-Protection: "0"
