---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        pod:
          securityContext:
            supplementalGroups:
              - 104
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/jellyfin
              tag: latest
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              GUID: "1000"
              JELLYFIN_PublishedServerUrl: "https://jellyfin.khzaw.dev"

    service:
      main:
        ports:
          http:
            port: 8096

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: jellyfin.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: jellyfin
                  port: 8096

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: jellyfin-tls
            hosts:
              - jellyfin.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 150Gi
        accessMode: ReadWriteOnce

      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true

      gpu:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
