apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mmcal
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: {remediation: {retries: 3}}
  upgrade: {remediation: {retries: 3}}
  values:
    controllers:
      main:
        strategy: Recreate
        replicas: 1
        pod:
          nodeSelector:
            kubernetes.io/hostname: talos-7nf-osf
        containers:
          main:
            image:
              repository: ghcr.io/khzaw/mmcal
              tag: 1771946720-f382eb2efb397ff65d56c53827cf149e4217dc01 # {"$imagepolicy": "flux-system:mmcal:tag"}
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  periodSeconds: 60
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8080
                  periodSeconds: 30
            resources:
              requests:
                cpu: "6m"
                memory: "20Mi"
              limits:
                cpu: "50m"
                memory: "40Mi"
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: mmcal.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          nginx.ingress.kubernetes.io/limit-rps: "10"
          nginx.ingress.kubernetes.io/limit-connections: "5"
          nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
        tls:
          - secretName: mmcal-tls
            hosts:
              - mmcal.khzaw.dev
