---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 15m
  chart:
    spec:
      chart: csi-driver-nfs
      version: "4.x.x"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  values:
    controller:
      replicas: 1
    node:
      logLevel: 2

