---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helmrelease.yaml
  - storageclass.yaml

commonLabels:
  app.kubernetes.io/name: csi-driver-nfs
