# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: booklore-mariadb
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-7nf-osf

    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/mariadb
              tag: "11.4.8"
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              PGID: "1000"
              MYSQL_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: MYSQL_ROOT_PASSWORD
              MYSQL_DATABASE: "booklore"
              MYSQL_USER:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_USERNAME
              MYSQL_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_PASSWORD
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "600m"
                memory: "768Mi"

    service:
      main:
        controller: main
        ports:
          mysql:
            port: 3306

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /config
