# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: exposure-control
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-uua-g6r

    controllers:
      main:
        serviceAccount:
          name: exposure-control
        strategy: Recreate
        containers:
          main:
            image:
              repository: node
              tag: 24-alpine
            command:
              - node
              - /app/server.js
            env:
              TZ: "Asia/Singapore"
              PORT: "8080"
              DATA_DIR: /data
              SERVICES_FILE: /app/services.json
              PUBLIC_DOMAIN: khzaw.dev
              SHARE_HOST_PREFIX: share-
              CONTROL_PANEL_HOST: controlpanel.khzaw.dev
              DEFAULT_EXPIRY_HOURS: "1"
              RECONCILE_INTERVAL_SECONDS: "30"
              DEFAULT_AUTH_MODE: cloudflare-access
              SHARE_RATE_LIMIT_REQUESTS: "120"
              SHARE_RATE_LIMIT_WINDOW_SECONDS: "60"
              IMAGE_UPDATE_CACHE_TTL_HOURS: "168"
              IMAGE_UPDATE_HTTP_TIMEOUT_MS: "6000"
            resources:
              requests:
                cpu: "20m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: controlpanel.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: controlpanel-tls
            hosts:
              - controlpanel.khzaw.dev
        hosts:
          - host: controlpanel.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 128Mi
        globalMounts:
          - path: /data

      app:
        enabled: true
        type: configMap
        name: exposure-control-app-files
        advancedMounts:
          main:
            main:
              - path: /app/server.js
                subPath: server.js
                readOnly: true
              - path: /app/services.json
                subPath: services.json
                readOnly: true
