---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flaresolverr
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/flaresolverr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  dependsOn:
    - name: ingress-nginx # still good to have networking ready
