---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ghost
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/ghost
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  targetNamespace: default
  timeout: 10m
  dependsOn:
    - name: longhorn
    - name: ingress-nginx
    - name: cert-manager-config
    - name: terraform-dns
