apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage-calibre # Kustomization name for dependency graph
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/storage/calibre # Path to PVC definition Kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
  timeout: 5m
  wait: true
  dependsOn:
    - name: longhorn
