# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 30m
  path: ./core/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
