---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyseerr
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/jellyseerr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default # Namespace where app runs
  timeout: 5m
  dependsOn:
    - name: local-path-provisioner
    - name: ingress-nginx
