# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb # Name of this Flux Kustomization
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/metallb # Points to the component directory
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
