---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/tailscale
  prune: true
  sourceRef: { kind: GitRepository, name: flux-system }
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: tailscale-subnet-router
      namespace: tailscale
