# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.7.3/charts/other/app-template/values.schema.json
controllers:
  main:
    replicas: 1
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: lscr.io/linuxserver/calibre-web
          tag: latest
        env:
          TZ: 'Asia/Singapore'
          PUID: "1000"
          PGID: "1000"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi

service:
  main:
    controller: main
    ports:
      http:
        port: 8083

ingress:
  main:
    enabled: true
    className: nginx
    hosts:
      - host: calibre.khzaw.dev
        paths:
          - path: /
            pathType: Prefix
            service:
              name: calibre-web
              port: 8083
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: calibre-tls
        hosts:
          - calibre.khzaw.dev

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /config

  books:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: calibre-books-pvc
    globalMounts:
      - path: /books
