
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluxcd-charts
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/charts
  provider: generic
