
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: fluxcd-charts
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/fluxcd/charts
  provider: generic
  secretRef:
    name: ghcr-auth
