# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/tailscale.com/connector_v1alpha1.json
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  hostname: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
      - 10.0.0.1/32
      - 10.0.0.38/32
      - 10.0.0.197/32
      - 10.0.0.210/32
      - 10.0.0.231/32
