# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/tailscale.com/connector_v1alpha1.json
---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  exitNode: true
  hostname: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
      - ${ROUTER_IP}/32
      - ${UTILITY_NODE_IP}/32
      - ${PRIMARY_NODE_IP}/32
      - ${NAS_IP}/32
      - ${INGRESS_VIP}/32
      - ${IRIS_VIP}/32
