# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ersatztv
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/ersatztv/ersatztv
              tag: latest
            env:
              TZ: "Asia/Singapore"
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 2Gi

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8409

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ersatztv.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: ersatztv.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: ersatztv-tls
            hosts:
              - ersatztv.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /config

      # ErsatzTV uses this for temporary transcoding artifacts.
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcode

      # Read-only access to the shared media library (same PVC Jellyfin uses).
      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /media
            readOnly: true

