---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blog-image-repository.yaml
  - blog-image-policy.yaml
  - mmcal-image-repository.yaml
  - mmcal-image-policy.yaml
  - rangoon-mapper-image-repository.yaml
  - rangoon-mapper-image-policy.yaml
  - ericaknight-image-repository.yaml
  - ericaknight-image-policy.yaml
  - interview-prep-image-repository.yaml
  - interview-prep-image-policy.yaml
  - retirement-image-repository.yaml
  - retirement-image-policy.yaml
  - blog-image-update-automation.yaml
  - mmcal-image-update-automation.yaml
  - rangoon-mapper-image-update-automation.yaml
  - ericaknight-image-update-automation.yaml
  - interview-prep-image-update-automation.yaml
  - retirement-image-update-automation.yaml
