# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 6h
  chart:
    spec:
      chart: metallb
      version: "0.16.1"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    speaker:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    frr-k8s:
      frrk8s:
        livenessProbe:
          failureThreshold: 12
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 6
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        frr:
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
        reloader:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
        frrMetrics:
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
        frrStatus:
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
