# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-uua-g6r

    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/librespeed
              tag: latest
            env:
              TZ: "Asia/Singapore"
            resources:
              requests:
                cpu: "25m"
                memory: "64Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: speedtest.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/hostname: speedtest.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: speedtest-tls
            hosts:
              - speedtest.khzaw.dev
