---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.2.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/sabnzbd
              tag: latest
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              PGID: "1000"
              SABNZBD__HOST_WHITELIST: "sabnzbd.khzaw.dev"

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: sabnzbd.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: sabnzbd-tls
            hosts:
              - sabnzbd.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /config

      downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: downloads
        globalMounts:
          - path: /downloads
          - path: /incomplete-downloads
