---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-media
  resources:
    requests:
      storage: 500Gi
