# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: booklore
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-7nf-osf

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/booklore-app/booklore
              tag: "v1.18.5"
            env:
              TZ: "Asia/Singapore"
              USER_ID: "1000"
              GROUP_ID: "1000"
              DISK_TYPE: "NETWORK"
              SWAGGER_ENABLED: "false"
              FORCE_DISABLE_OIDC: "false"
              DATABASE_URL: "jdbc:mariadb://booklore-mariadb.default.svc.cluster.local:3306/booklore"
              DATABASE_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_USERNAME
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: booklore-secret
                    key: DATABASE_PASSWORD
            resources:
              requests:
                cpu: "200m"
                memory: "384Mi"
              limits:
                cpu: "1000m"
                memory: "1536Mi"

    service:
      main:
        controller: main
        ports:
          http:
            port: 6060

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: booklore.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: booklore.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: booklore-tls
            hosts:
              - booklore.khzaw.dev

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        accessMode: ReadWriteOnce
        size: 8Gi
        advancedMounts:
          main:
            main:
              - path: /app/data
              - path: /bookdrop
                subPath: bookdrop

      books:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: calibre-books-nfs
        globalMounts:
          - path: /books
            readOnly: true
