---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system

  values:
    csiDriver:
      name: "org.democratic-csi.nfs"

    controller:
      enabled: true
      rbac:
        enabled: true
      replicaCount: 1
      hostNetwork: false
      priorityClassName: ""
      externalHealthMonitorController:
        enabled: true
        resources:

      livenessProbe:
        enabled: true

      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: "next"
          pullPolicy: Always

    node:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
          pullPolicy: Always

    storageClasses:

    - name: truenas-nvme-downloads
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      parameters:
        datasetParentName: nvme_pool/torrents
        fsType: nfs
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    - name: truenas-hdd-media
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      parameters:
        fsType: nfs
        datasetParentName: tank/media
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    - name: truenas-hdd-config
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      parameters:
        fsType: nfs
        datasetParentName: tank/config
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    - name: truenas-nfs
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        datasetParentName: tank/k8s/storage
      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:

    driver:
      config:
        driver: freenas-api-nfs
        instance_id: "truenas-nfs"
        httpConnection:
          protocol: http
          host: 10.0.0.210
          port: 80
          allowInsecure: true
          apiVersion: 2
        zfs:
          detachedSnapshotsDatasetParentName: tank/k8s/snapshots
          datasetNameTemplate: "{{ .parameters.csi.storage.k8s.io/pvc/namespace }}-{{ .parameters.csi.storage.k8s.io/pvc/name }}"
          datasetEnableQuotas: true
          datasetEnableReservation: true
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: 10.0.0.210
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: ['10.0.0.0/8']
          shareMaprootUser: ''
          shareMaprootGroup: ''
          shareMapallUser: root
          shareMapallGroup: root

  valuesFrom:
    - targetPath: driver.config.httpConnection.username
      kind: Secret
      name: truenas-credentials
      valuesKey: username
    - targetPath: driver.config.httpConnection.password
      kind: Secret
      name: truenas-credentials
      valuesKey: password
