# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: ${UTILITY_NODE_NAME}

    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/prowlarr
              tag: 2.3.0.5236-ls139
            env:
              TZ: "${TIMEZONE}"
              PUID: "1000"
              GUID: "1000"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"

    service:
      main:
        ports:
          http:
            port: 9696

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: prowlarr.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

        annotations:
          external-dns.alpha.kubernetes.io/hostname: prowlarr.${BASE_DOMAIN}
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: prowlarr-tls
            hosts:
              - prowlarr.${BASE_DOMAIN}

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        size: 1Gi
        accessMode: ReadWriteMany
