---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 1Gi
