---
apiVersion: helm.toolkit.fluxcd.io/v2b
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/transmission
              tag: latest
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              GUID: "1000"

    service:
      main:
        ports:
          http:
            port: 9091

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: torrent.khzaw.dev
            paths:
             - path: /
               pathType: Prefix
               service:
                 name: transmission
                 port: 9091

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: transmission-tls
            hosts:
              - torrent.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: app-configs-pvc
        advancedMounts:
          main:
            main:
              - path: /config
                subPath: transmission

      downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: downloads
