# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tunarr
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        pod:
          securityContext:
            supplementalGroups:
              - 104
              - 44
        containers:
          main:
            securityContext:
              privileged: true
            image:
              repository: ghcr.io/chrisbenincasa/tunarr
              tag: latest
            env:
              TZ: "Asia/Singapore"
              # Force the modern Intel driver
              LIBVA_DRIVER_NAME: "iHD"
              LIBVA_DRIVERS_PATH: "/usr/local/lib/x86_64-linux-gnu/dri"
            probes:
              liveness:
                spec:
                  initialDelaySeconds: 30
              readiness:
                spec:
                  initialDelaySeconds: 30
    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: tunarr.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: tunarr-tls
            hosts:
              - tunarr.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 5Gi
        accessMode: ReadWriteOnce

      gpu:
        enabled: true
        type: hostPath
        hostPath: /dev/dri
