# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/all.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nvme-downloads
  resources:
    requests:
      storage: 899Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-media
  resources:
    requests:
      storage: 8Ti

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: books
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 20Gi
