---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nvme-downloads
  resources:
    requests:
      storage: 899Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-media
  resources:
    requests:
      storage: 8Ti
