# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-7nf-osf

    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/bazarr
              tag: latest
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              GUID: "1000"
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"

    service:
      main:
        ports:
          http:
            port: 6767

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: bazarr.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: bazarr
                  port: 6767

        annotations:
          external-dns.alpha.kubernetes.io/hostname: bazarr.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: bazarr-tls
            hosts:
              - bazarr.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 1Gi
        accessMode: ReadWriteOnce

      media:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: media
        globalMounts:
          - path: /media
