apiVersion: v1
data:
    password: ENC[AES256_GCM,data:4xZtC6GyfknCmYLz9Fa9HJ3Olj0oNcBA,iv:T4Q+wCkOVWmp3h3sn6OGtzvBE2N1NGYAqYkKliR0xp4=,tag:2mX5LKJf2CI5coMJU+Bing==,type:str]
    username: ENC[AES256_GCM,data:nFYcng==,iv:E0+0urjL6g67srLZ3CgqqbstHTBEQYB1YxEw6toXXRM=,tag:9YeJIh/shKcC1FBsRSI3dg==,type:str]
kind: Secret
metadata:
    name: truenas-ssh-credentials
    namespace: democratic-csi
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwamVGQ05rV2xHYzVWMjdF
            TXJDUEgydFFoMlJKUDgxTVpwV1pjSFYxcUZVCjBrYkhNUlpkR0JlM3VsV0Q4YjNI
            dEg0b1hOdUMra2dEMFFTcWtYWWwvUmcKLS0tIDluTG15T1kzNDZsY3huUGJXVVFm
            eHpHQUVtZnV1SG9sK3pOa3B3NXhwd0EKJ26+fyaECQlrKs9dZMRpmZsTIQ9SUyFh
            Bpcq9d7gJGWLOkz1Fpn5bR/UNfI73iNBPg2e/Ucm6RKeodGqm7yNrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T10:16:08Z"
    mac: ENC[AES256_GCM,data:U9mpcoIlDxBwq5Z0Z5hVfd0YrOMdJrUTUH2MTU3YwQA9ehOnX58KaOnDOAzOff4hyJnKLkbYxTei2BdfTvzwWPTQV0imM2uDql2aGgncH5Om5w/+JEf80PO3+HYCbs9QcYwqMxq08kg+IbSW/P9rKdUEMFljSx6SZD5QgL2+OQI=,iv:BD1I7DLix0WDoWUlu7B5dgu7FuEhfkl1vc0cU8ACce0=,tag:XqAUOkGkhp06t0DU2efKlQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
