# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-uua-g6r
      dnsConfig:
        options:
          - name: ndots
            value: "1"
          - name: timeout
            value: "1"
          - name: attempts
            value: "2"

    controllers:
      main:
        replicas: 1
        strategy: Recreate
        containers:
          main:
            image:
              repository: louislam/uptime-kuma
              tag: "2.1.3"
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 300m
                memory: 512Mi

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 3001

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /app/data

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: uptime.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: uptime-kuma-tls
            hosts:
              - uptime.khzaw.dev
        hosts:
          - host: uptime.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: uptime-kuma
                  port: 3001
