apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  interval: 30m # defines which interval the Helm repository index is fetched
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: uptime-kuma-helm-values
      valuesKey: values.yaml
