apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      # hostNetwork: true # Use host network to easily advertise routes on the LAN interface
      serviceAccountName: default # Or create a specific one if needed
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest # Use official image
        env:
        # Get Auth Key from K8s Secret
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-authkey
              key: AUTH_KEY

        # Define the routes to advertise: Your MetalLB Service IP
        - name: TS_ROUTES
          value: "10.254.250.0/8"

        # Optional: Add Kube Secret storage to persist node identity
        # - name: TS_KUBE_SECRET
        #   value: "tailscale-state" # Name of secret Tailscale will create/use

        # Add necessary linux capabilities for routing
        securityContext:
          privileged: false # Avoid if possible, use capabilities instead
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]

        # Readiness probe could check tailscale status
        readinessProbe:
          exec:
            command: ["tailscale", "status"]
          initialDelaySeconds: 5
          periodSeconds: 10
