---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale-runner # Name of the Role
  namespace: tailscale
rules:
  # Permissions needed for TS_KUBE_SECRET state storage
  - apiGroups: [""] # Core API group
    resources: ["secrets"]
    verbs: ["create", "get", "update", "patch"] # Needed to manage its state secret
  # Optional: Permissions for Tailscale to create Events (addresses the warning log)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
