---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-4.2.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/qbittorrent
              tag: latest
            env:
              TZ: "Asia/Singapore"
              PUID: "1000"
              GUID: "1000"
              WEBUI_PORT: "8080"
              TORRENTING_PORT: "6881"
    service:
      main:
        ports:
          http:
            port: 8080
      p2p:
        enabled: true
        type: LoadBalancer
        ports:
          tcp:
            enabled: true
            port: 6881
            protocol: TCP
            targetPort: 6881
          udp:
            enabled: true
            port: 6881
            protocol: UDP
            targetPort: 6881

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: qbittorrent.khzaw.dev
            paths:
              - path: /
                pathType: Prefix

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: qbittorrent-tls
            hosts:
              - qbittorrent.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: app-configs-pvc
        advancedMounts:
          main:
            main:
              - path: /config
                subPath: qbittorrent

      downloads:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: downloads
        advancedMounts:
          main:
            main:
              - path: /downloads
                subPath: qbittorrent
