# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - monitoring-cname.yaml
  - servicemonitor-kubelet-resource.yaml
  - grafana-dashboard-node-power-estimation.yaml
  - grafana-dashboard-node-capacity-overview.yaml
  - prometheusrule-power-estimation.yaml
  - prometheusrule-node-capacity-overview.yaml
  - servicemonitor-exposure-control.yaml
  - prometheusrule-exposure-control.yaml
