# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/service-v1.json
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-cname
  namespace: monitoring
  annotations:
    # Create `monitoring.${BASE_DOMAIN}` as a DNS alias to `grafana.${BASE_DOMAIN}`.
    # external-dns must watch Services (`--source=service`) for this to work.
    external-dns.alpha.kubernetes.io/hostname: monitoring.${BASE_DOMAIN}
spec:
  type: ExternalName
  externalName: grafana.${BASE_DOMAIN}

