# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/service-v1.json
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-cname
  namespace: monitoring
  annotations:
    # Create `monitoring.khzaw.dev` as a DNS alias to `grafana.khzaw.dev`.
    # external-dns must watch Services (`--source=service`) for this to work.
    external-dns.alpha.kubernetes.io/hostname: monitoring.khzaw.dev
spec:
  type: ExternalName
  externalName: grafana.khzaw.dev

