apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-receivers
    namespace: monitoring
type: Opaque
stringData:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:ZrIFaiH4d/DhUcpiqe7bfxgP4VqiG0evxOeGucrEGa1ucxXxvxCRrubeNPOxJOCSHeJ1NgTr8QeUuOBwYMDcbPE67Z7sQoFP+OJtjBJ3mFR9991VOcmiMt8goOaLKFHRe5d+D18K1341OORUkpCgqvqZXdLio197qQ==,iv:jJmvv/6A6/x17Wwe6IlqR6Dn/uwKp62tUNX3zvdv+a8=,tag:B44FETppuZnNrCRbYVytXA==,type:str]
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:hWkxLc3BtmF8x/LRHzmgNdc3Heb4BcH45GQQyChrhF2Aq4rtWMrd6PIdg8HSog==,iv:FhkOe0fXUUcK+WjPBNPf44T0soTQuHGbkkO66JIDZsM=,tag:VrZmtj42P0rt9Md8QXQxaw==,type:str]
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVWxOK3g4dGdBa05Dd2dQ
            eEs3VGJkRVZuWTRKVTZUQ1p2eTdwVHB2cm1nCkYzZlY4b296UU5VSExNc0pZaEl4
            V3BUZG1FREs3R3Z1UFA2TkVaaHFJaFkKLS0tIC8remFvVW1VRzlZTU9NZXl1TjhI
            MGNsb2JtTjZlbC91THo4VnNzb1FCa3cK/GBmoo04rap1s+kUdgpq6UNqsE4B/h+c
            /sPAa75NRsx/if60yy6yVvLY6DF7pbT9zncoL9kJaosEcxqaWLe9nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:52:38Z"
    mac: ENC[AES256_GCM,data:qe/n5nCKMi0RCdvJCPlbs3Qqbj4qfYk4u+5m4rP5fL80ZFd4Huo3LulZb6LHOtExeoSvi6Ba7xa2UVeAEcjJ9uXVhGP68L3I1WUM7aElcXj158nyuuaTd4XqM2cS0IYx0z1IyXTtelaEzAD3aY7KF/Ark4hfcAsU4Xy2ilBd0W4=,iv:NjTIs+9JESKNJE0qGK6w5ALnV+XT9nn7mXSIqQWK0m0=,tag:izGmIFuk4eLV389v5dbY2Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
