# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          nodeSelector:
            kubernetes.io/hostname: talos-uua-g6r
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: v0.107.56
            env:
              TZ: "Asia/Singapore"
            resources:
              requests:
                cpu: "25m"
                memory: "128Mi"
              limits:
                cpu: "300m"
                memory: "512Mi"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 80

      dns:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 10.0.0.233
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: adguard.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: adguard.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: adguard-tls
            hosts:
              - adguard.khzaw.dev

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
        advancedMounts:
          main:
            main:
              - path: /opt/adguardhome/work
                subPath: work
              - path: /opt/adguardhome/conf
                subPath: conf
