# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        strategy: Recreate
        pod:
          nodeSelector:
            kubernetes.io/hostname: talos-uua-g6r
        containers:
          main:
            image:
              repository: adguard/adguardhome
              tag: v0.107.72
            command:
              - sh
              - -c
            args:
              - |
                set -eu
                CFG=/opt/adguardhome/conf/AdGuardHome.yaml

                # Keep key DNS performance settings in GitOps so runtime changes do not drift.
                if [ -f "$CFG" ]; then
                  sed -i -E 's/^  address:.*/  address: 0.0.0.0:80/' "$CFG"
                  sed -i -E 's/^  upstream_mode:.*/  upstream_mode: fastest_addr/' "$CFG"
                  sed -i -E 's/^  fastest_timeout:.*/  fastest_timeout: 1s/' "$CFG"
                  sed -i -E 's/^  cache_size:.*/  cache_size: 16777216/' "$CFG"
                  sed -i -E 's/^  cache_ttl_min:.*/  cache_ttl_min: 60/' "$CFG"
                  sed -i -E 's/^  cache_ttl_max:.*/  cache_ttl_max: 3600/' "$CFG"
                  sed -i -E 's/^  cache_optimistic:.*/  cache_optimistic: true/' "$CFG"
                  sed -i -E 's/^  upstream_timeout:.*/  upstream_timeout: 3s/' "$CFG"
                fi

                # Keep DHCP disabled in the Kubernetes deployment model (router handles DHCP).
                if [ -f "$CFG" ]; then
                  TMP="$(mktemp)"
                  awk '
                    BEGIN { in_dhcp = 0; replaced = 0 }
                    function print_dhcp_block() {
                      print "dhcp:"
                      print "  enabled: false"
                      print "  interface_name: \"\""
                      print "  local_domain_name: lan"
                      print "  dhcpv4:"
                      print "    gateway_ip: \"\""
                      print "    subnet_mask: \"\""
                      print "    range_start: \"\""
                      print "    range_end: \"\""
                      print "    lease_duration: 86400"
                      print "    icmp_timeout_msec: 1000"
                      print "    options: []"
                      print "  dhcpv6:"
                      print "    range_start: \"\""
                      print "    lease_duration: 86400"
                      print "    ra_slaac_only: false"
                      print "    ra_allow_slaac: false"
                    }
                    /^dhcp:/ {
                      print_dhcp_block()
                      in_dhcp = 1
                      replaced = 1
                      next
                    }
                    in_dhcp == 1 && /^[^[:space:]]/ {
                      in_dhcp = 0
                    }
                    in_dhcp == 0 { print }
                    END {
                      if (replaced == 0) {
                        print_dhcp_block()
                      }
                    }
                  ' "$CFG" > "$TMP"
                  mv "$TMP" "$CFG"
                fi

                exec /opt/adguardhome/AdGuardHome \
                  --no-check-update \
                  -c "$CFG" \
                  -w /opt/adguardhome/work
            env:
              TZ: "Asia/Singapore"
            resources:
              requests:
                cpu: "25m"
                memory: "128Mi"
              limits:
                cpu: "300m"
                memory: "512Mi"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 80

      dns:
        controller: main
        type: LoadBalancer
        loadBalancerIP: 10.0.0.233
        externalTrafficPolicy: Local
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: adguard.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: adguard.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: adguard-tls
            hosts:
              - adguard.khzaw.dev

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        accessMode: ReadWriteOnce
        size: 2Gi
        advancedMounts:
          main:
            main:
              - path: /opt/adguardhome/work
                subPath: work
              - path: /opt/adguardhome/conf
                subPath: conf
