apiVersion: v1
kind: Secret
metadata:
    name: anki-server-secret
    namespace: default
type: Opaque
stringData:
    SYNC_USER1: ENC[AES256_GCM,data:OMwFf9hzu5iVEM+ZvmNddYU00aUEzefr2dfAIg==,iv:exUrImbcrbFHmwBlKnbc8VLWqsi3zylVnyKfg+rPO7c=,tag:YUQRgKWZCOmlm52TBzfclA==,type:str]
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOXJYZGdNNm1LaGErNnVH
            YmMxbU1ZeDZqWHJMQXlKTFJPRVFaK1pXYkU4CndrQ1lCNWRVOEo1TUVaYjQ0RU1N
            NllUclNFYXl6NnZnNUpPMFdTYlZITVEKLS0tIFBNSjF1TUhNN250cERYTFVSMWFD
            WVVuN0FWaHQra0QvNitkTTRGU2Nzb00KGf6QiL7X+8DdEvIP9gKfTSEgGo6MmpaK
            PYGd3RwWd6E/QKU7YDTULhH1deIGL9iFkH3a8cEc/kiN36pq8qPQHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T12:03:54Z"
    mac: ENC[AES256_GCM,data:5ltY2KJgy2dWTgyVQRjXh3snjo+dpJEi7yPdxKvI3LLRqj7SdVELFtdOFEeeKw8KXqvlbIbtFfF0ZkTHt7Od7rDpOKW4WoD+y/1+3UXbhFIOFKEC2GTdOsGdvzZ8QHLQ1T/Vf2liAb+z6myZth1/JdBAyVuZh9E986Y0TGOpRBw=,iv:Xr2res3dt5F6qhjW08ELvZLKkfXpItl/QaZAlsJKDOE=,tag:m835R875fuCjC34h81n8ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
