apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secret
    namespace: default
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:Oz3KDuYeX0tQ,iv:ocDbPCbSBwUT06AqOzjJeIvh+hvOr4JO64im536ckYY=,tag:Hr8KwveaqEE8LLWbunGhmw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:nInkX7pQHSIfPNs0RPGzw307JRYqZmQh+b/jFNzePxoOs6dweCuLVUn+A9FzrV8m,iv:gI6ckM2ZOcqrMY2iltEAxFoYK+t+NMjYauPFzcFuw18=,tag:AZJqaEReCP1l7KUjg9rYSg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:/L4VGAlP7K/l,iv:VUjCd7NJeOghU9ZsEIYVEp1FwKlMs0fdDCt9NNuCaIg=,tag:DuUAmxChrCmieITdRTsqRw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:sdYGIsNLM9fXAr07VvRlFQ+ZHAPkZAuDHbbZima9nxQI3KjdMxRdo2f0Rbh5dRWKv23CUpm/dz0jxgtjHKviEg==,iv:UnazaTSlEbjn6yXOsqgo//flr+hIJIFV0A/oQejPsic=,tag:aOLdmRY+ThnIAphhZNX66A==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:pOB4YjlCSSKRqa+mpUerPFOuArlCq6d4omszZfj5AuY=,iv:V9lR2ZtIqHvdn6epQuuh0xLODhruREzROfRDomnMXj0=,tag:09F2LbReHuhqAr8lkdlWlQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:tSZi,iv:V14aret5Rb4HyPlEOknsExU+hLUmQe2tViB6mhbQ4mQ=,tag:peecLimhkY+0XURDgN4k6A==,type:str]
    ADMIN_NAME: ENC[AES256_GCM,data:v/ZqSM5Il3pCEQ==,iv:S88C46lNz+jml+eVYGubTqYf04BvP2JlJaOEVjnIKHY=,tag:g3Zz9pfNxLyqTTbzinz3DQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:HuY2mzxHD5i9NodifBYYdCg=,iv:PIzARlZl3RTv0Cgb/hJStdxAmr7Jp99H31TLMACNn1g=,tag:IcvfuLP6XbqLZ6C5vSYD7Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:9ImPMUGb0bq6L718ntZUbscAyQgFHXbCO1VMrKLJh3bMQbmJa/hxjjliXozX,iv:tlk8bffmC/TZG6HYvAnmQaA14wL73rDT1+cGbC18rZI=,tag:dRzo+SketDdaOvs+OImFFw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aEllT3o3aVlTWXp3TWRn
            ZVEvNTRQWnQ3ZUdpVndObDIxV004U2JiUFRFCkJndGhBL0o3eEdGemw0WWFTSHlu
            ZklaWm1wZURud3kwSUZNT2ExMzZ0eFkKLS0tIFQwSENtUDhJd1gzRHlrTG1WbmJ1
            VlNuZW0ybDV2dm80dDRDemlIS1VlL1kKSXvSqhCAuWAn7HsRWrP6ElqiougnEVQB
            M5WzgHsZXmI/Q5PauWoET4mwTaoYiVJfIPKLfaPGHsix7QnqWaF91Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-17T15:03:05Z"
    mac: ENC[AES256_GCM,data:Vf+XjrHOSzP/J5Ger+gie1hw6xQpHInyKt2V/GdsIv7rkooG/pgBIVZwEE38dVV7++2FCZ9VXhowRc8C7KenyZ+xMh62noYNhjGv7z8iVqTR6KLJJjVzTE4az+3GiDcTiR7+y9C5GVjzZookgDXKgEJCnOkqaOGc0C02hnfxBx0=,iv:LgydS0MHBkHdJhnq+3faabo5KiyA5PIKtrr+PfjZx10=,tag:afPmpu1uQDA2f0UHVW+yow==,type:str]
    version: 3.13.1
