apiVersion: v1
kind: Secret
metadata:
    name: dynacat-github
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:A9+p+GamlUWn/WI5iCNkAlySNq79tFXwIJqEg6a8o3J23xm5qP9LV5wPWxC3w+Hoe4ebdGPF7vFgHrtA20+Xras7gJIsMfMKvtyzXi1hDIidZd0pguJdB4pwnqWL,iv:vpXU2U+hUTPHElKedmA5K9DlpxmvCOICPu1OsqpzUJE=,tag:NDKCcqSezPArUfwswbaxHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreGtQazc5TEp3NTFOOUp4
            SEZDY3VYWGhVNFVQbFBpcmlkNkRKR0h4cFc0CkloVzJXY1Z2M0ZITWR2UlVhU3Ix
            ZXVWWEtORkwyY1FyTXpCU3k5VUtDSmcKLS0tIGkxMFNQR1pyeFEwVm9RSEF4am1I
            SXhKVFdiSC8rOWE4MDJLcTcwdy9JWU0KJOsABwKaYhpAMKw75ydd/7WDNV/k1US9
            6Fk1jhnXzCVycXIVyMEKKcNfICyuYHeedjs9R2RlwbOgN4OlF4Xt4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T15:48:15Z"
    mac: ENC[AES256_GCM,data:DXGWuqjim2YVoP5us7Z+iBiaUxybc3/xnJPvTyP5hKwnHVLQISobGmBiqh1elPbHXf4LbbmQcNfB0dz/CVDy9OF4YtSdb0L7NsQgWrHXeiR1EfitJTuncX5efV3rZ4U+PmghPu3ELXp3r1fCZtiBEAtpXuyGVN2Vt7N1Uy7eof4=,iv:Sx32PjKWHMSykJHvFxZVSG3mrUi90pUpSAcO3W2/sg0=,tag:IwchxtZ4ilb4FCRNlHRDnQ==,type:str]
    version: 3.13.3
