apiVersion: v1
kind: Secret
metadata:
    name: exposure-control-github
    namespace: default
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:D1Bgqa7L/q7ga5bdK4W8ghHshAn8RUG9POGG94ep35k+4srzEJNR8g==,iv:tnEM+9VkMnSI0C0Gs+ju1if9Y7UWFxW9153Ju8fbvFo=,tag:7cl+U53FwVmRcl3sWSqnzA==,type:str]
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWWlsRWs1c0dxWElEMzZn
            UHFLbVd3enB5WnRyM1Y3cjAxTmU3RXA3b1FFCjcwQ25WNzBmRUdLY3NyYXIzQXNt
            L3hZUHNqc1RzZG10NGtNRjNaOWsrcVEKLS0tIFBaSC8yVEhqcUM2bzVsZlU0eEVz
            aEJGODFKUkl4cFM2dC9lckpHYlliZlkKZAN1yJ4vx1jGtacQc9Co/5Xo0K07gnAR
            Blwagi44HXEZh9QE9ycMGXt6QUPqfF36xn7LkVv3lgQl1qjqW3gl+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T14:47:40Z"
    mac: ENC[AES256_GCM,data:sJIEvG7YE6P4rNYy4aLoBXHWHnV5r+YIkX959X2h7iWQiV758GQQ4WXv2X7exUXev1zj0ted5mi/BS7joVAGQGnqejuQVDlGWZMAYEyS6RWMXQqss47tZtvG5Ja0mYyeFREc1TfrZZKvBz1j/R5zi9VBUZQcnvN9qRwnEtt9KVs=,iv:IwbTdzEEAWQRYX78qayKiCRQZprxmFSkmAB6zqRBGHk=,tag:YfOj0GRBfOJV7T/2wKE4+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
