apiVersion: v1
kind: Secret
metadata:
    name: exposure-control-github
    namespace: default
type: Opaque
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:zUWeniDGLmzTCwKyGPf0EQpLj10bO8MoEBiGiP+yA1SLaFUUmLWaYw==,iv:eYzMqSrEhaEeZYcZ9WdcDWeWotplHvVjl4xC3h92ahM=,tag:z8XT+3mEPitdblDZlilpIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMXB5b2RReU1NRTViSENR
            MWttWjQ0QUR5YlQ3V0t0NmtncGgxVmJGaUNzCmtDRWwvWURidjExUWJWcXhzSEU3
            VW5yNzJMYS9wSWplSWNQdms5TU5wODAKLS0tIGpXRzA4dTgyUXJLam9XdVowQk1p
            YWU4VUdML1NBMktvdThnamFTVUFVV28Kz2nxP2Avfceznzn+mSbU+sCrQzTUOjPt
            g/wAC50AWQajpgKjEBblKQ2LIsy5BH7dDucFcfc+xZd4hly8HdZn+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T15:41:12Z"
    mac: ENC[AES256_GCM,data:7VTKpMuouBO7M2X5wPZBGCcHqpD5hJOzjPUm5QnOkKIeXcuR2TtxXCnfzHfsihXeib6nzkcI4DfX6RDg6PxqVKw8CeNplBpWXcEl8fnJenp2gI5YAnPFZkXNoCOnV570pQIQxd4Git9LYKAdC7qOFKObDkPXDLamR6kjEC427dA=,iv:NcMzlcNPHb0UO9tgwzMhDYPQJKGJVtNA533x9VSvayY=,tag:he3/pkVaRgsR3RWSIoaF3g==,type:str]
    version: 3.13.3
