apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:5xVElQ0P+j8th2/sa1j2Bowskh6V6qyPqfmwJHxi+e4c4ZO8GBfNKsk5H44HEqk0wEhDCg403mYbg/lxSxFHrC7OKJ3BdAusG4yZkE+gA1v7tm0BnNHe84irSLXHNDmNTYwda0UOzFd0Y0Ti3DRBTvl0QXcyBacqPHjuvB/eb/teRt5c+l43zzU1NxZyIz0v6AdOXjLPS8NGS8otjo7RPL5BvYPQE5P07jTd9ZgrPDgItWwdnGGuW5BIPTHsE3i2/DAzRWjbUtHl3jxmy3z3QJB/a5d7JBjDadMwPixf2Msdwi5E,iv:8ZQZG9H2p40d9I24Aq0lz0ARX2i9OEWdTenWM2LUh5I=,tag:2XUPJ1BW+jaaFnYAq98FLA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySzQ4alpiUW5WQUxhWGll
            Qk9ZOGd5dHVleEppaWI4cUpDQmlnYUQ1Z1g0ClE1THNYVzhwS1lpTTgwSy9TODc4
            dnlGMkRtck9HVzM0UFAwcTFYUytjL0EKLS0tIEo1L1ZFOHRXeEpKYkpqL0VaN1E4
            WDhsR2YyZEExNkVXVHNyVEV5eGp1M0kKR6rhLOH3aWA/cTcLKzU/jlvrEywbnX1M
            idd5BRLpoOChyyViXy0yf3aN+7aID/REhFxRIXKSWbP8kdDM+PRgjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T20:37:22Z"
    mac: ENC[AES256_GCM,data:zIe8g7UUg7pjfjLk1J2i9NInuCH6Vs2u04rs9xgHXDCESGOx/cOVDOevUCXs3cpL+vP2nslylNenal5hDgFL9nLEde3tttzz9IfXuOKVgipHJH3ctm5ZxusiMmDz0MyD6iHZuIq+Hwh8bhCRe89h1mPO4N06UGc8buIitqkuU0M=,iv:CNVpVwNipkhiIedplWWdfZXofsuY2PuvYIQWQnN+3vQ=,tag:0j77nizpcVNXK0plOnEV0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
