apiVersion: v1
data:
    BAZARR_API_KEY: ENC[AES256_GCM,data:D09f7TD3QJn5JIkxsCBjCH8nHmFCPxi5FaSpFwQp+YhVKkSsnG6wHH1eD6E=,iv:4jy14dNQdHnQH4jDiTiKZEMH9BOx3Ze7noOUZ6WXyrQ=,tag:PqLGzLm9mNqQ1OcLHzWvvg==,type:str]
    FINNHUB_API_KEY: ENC[AES256_GCM,data:ZEasPo6qQhodEcAlLCx8+n6rOsSa40BdSyL9X96CWW+nJLASXWDIBuOIYZzelfdGM+FlPCCRgr0=,iv:98BNUyGBGDRURdcUaRY+VPoWmfxqjSXCbo5wVqSQTNs=,tag:vTYX2QxmKdpZWlePkNA56A==,type:str]
    IMMICH_API_KEY: ENC[AES256_GCM,data:/A0a+lx8k2Tq8jGELFVQoYmVWGsyi+CKhk/YCcyzYM6gJZXwplavX9j6IiAqiMbzdq1KIL8RpP4=,iv:Oan8ndhtLpnKFwX9vqJYHXjajWu33PPLQJit/N1ajRI=,tag:KQG/5p662K2/SVZHGonztw==,type:str]
    JELLYFIN_API_KEY: ENC[AES256_GCM,data:tgl/2iALS+rzVwUaiW0L09JdqUGOKHbtpurk0xslQTrkLFmaCg0GbxZb2d8=,iv:a23cj+r7toA6TU6FP0lF4lnxxmLRMYihVsSD4lBY7oY=,tag:wZKOONxnAvb1X0al7P6wow==,type:str]
    JELLYSEERR_API_KEY: ENC[AES256_GCM,data:+VN8mddOg3YJtIaoxDd+eJpNb01Fk6OkAPAeGUTI/5ue6T4YFrrbm9vmX4jv41wKdpGC1/sGBdonvbCgX1N1eOY+N3w1ObZ0UEcX0sd8M+7pxyCCT/QDp+5FXkc=,iv:QMi5Q1w15lw1U6/10Xk8yB1Xgf9gzjrjGQu1VC974IU=,tag:kD3vNmCUQmq1/lgmcksW1Q==,type:str]
    PROWLARR_API_KEY: ENC[AES256_GCM,data:wa03nFS638xPYykc+GBfqIl8b5F2cRD40oj2Jhmo+1/kUzyV/9DpwfGw1ho=,iv:3juGw+z4MZ0XHsV7y2GQMNf0pLtmN38WLxGMThT900A=,tag:Y4drTNFrI64Ylv3G62NeZw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:atbnuL5ZTQUxvzeSlwI2bQdY5BZxS3pv2gAgAZjnixu5m3Wwkv29guqfUu8=,iv:cBiCp/bFBwU4ps/6H5ZrcDKqggAPUpBVemeO+DEtpc4=,tag:2YNA7i9W0jDv92UjRMHQOw==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:N8R7J36mh7fycy/9jHyJ4U8Lk9GIjsBP0fSF0sKrQcn2OuKhVThpakFPzQM=,iv:WN3HpENBPuMBty/F8Mb5jT0X5y5djbKtVYsWnMvarVU=,tag:qC2gs/Vk70feCY0GQmcoEg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:utNqRKVoGv0LpCjLySVq4M+QYYJmqGpDsisB9GJDzfsc6EV3sp9OYOcVtY4=,iv:ebcNeq2H3Gx1GTjTOkzaPXpXgMT/U1ZlPPxMRcQC+MI=,tag:yXsnN0w8ZAMA3Z6JZwzErQ==,type:str]
kind: Secret
metadata:
    name: homepage-widget-secrets
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cE1hZ0kxOXl0a0Mvek1O
            K2RncTJIVWFWZXJ4RklDU0RyQXQzRk5ib2o4CnhoQWlNdFVIWUV4RU5CcXEvV1Nm
            SkNTeWhHMDNyRFhzWHJ2RGpyRW4rM0kKLS0tIGxtSjRtYlJza3JqUUg2VmFqbDhj
            NXp6RzhoeWlsb05IMnNDNWNzZXRpck0KgPSkhKKG9awBhVZZW7pCBkGu+TnealnP
            R63FhgdMmAdv+TE0Mvq0JHUKa0m8II02FCoiBs71OyqQWW83G3kyNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T13:34:59Z"
    mac: ENC[AES256_GCM,data:7HKx5temuS3njy2UQtGX8M+rmHmpkvCT9hBLH8ZP3S9BrNOeSMguSjB0DxxDbN7/dVF+kZDDFRxtlLBAolABja+Uda4+lYtSJp23WFSq+km30eNzssS+wsGuS8jkCL1WOaERL3ToSdTWldlTEFRdzxuoLVVw72nCVYmwHXPK03A=,iv:BXj7P7RdbkrSkdnAQITWiM4pdQnI6pqcVkv6ao+81JA=,tag:5r/DHJDKcS2V/rY+29Yu1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
