apiVersion: v1
kind: Secret
metadata:
    name: multica-app-secret
    namespace: default
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:8ECnLogMCDLeqEQHpArO5CMJJ2eSxt8PYPrPDn9l1FrwU2zmLBwKFmMO0tyRyS6WzpqbIxTfuPcQsjG74Cz0hw==,iv:vtSpzWhp5G3952FwUC7quagugNV/QF8d6bk/Pwb4V7U=,tag:WB/bOkywHP28LXnI+kX7yA==,type:str]
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDTGlFR2REcmYwaE11U3dC
            SHlqRk5wYVpTaGNJSWZiZEFQeVdHWnNFd2xJClZmTnk2VHN5eVBJZjR3RmJIVVB6
            clBtMStIeU9XRG9sdUZTQVhrUWxuamcKLS0tIExGR1lBUTZvaEFKNTZGTno1cHhm
            SUFVSXNZWWVDZGo4Tk8xU01FdmI1MGcKOen3/28sk5eoQi+XeNpySuzDgSuUmzw2
            x0poz92uYHhNw/tu/VLKwT+GlI5iy0yffVNAZ395IRdrRl8HxZHlJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T16:03:00Z"
    mac: ENC[AES256_GCM,data:Sdj8SIQ99HZGPaxPINnezcADVMxzeFp2W7Q1pgncynV586HvYoUsOkwGsz5bx26xw3WvFkE4BWCZ+wv9u1ITJh+DWbOI5MSBHLbZA00eb40Abz7QPaNTyWpY+/vDdviqJ2CpRVRojQueGQhylyThmzlPoB05hDiM6FRKbL1LCBg=,iv:TCNEHcGuvvMytz6Kr6/Uai6HO9gWswJUmZ1rOp565+A=,tag:AyjYA95/5gkuPPIRtisLpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
