apiVersion: v1
kind: Secret
metadata:
    name: multica-db-secret
    namespace: default
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:Mc2Ok9GcTg==,iv:Hpj/7995yzAGZhOCtfg8rCXD9s5KqOP8+7mvFGiHzcg=,tag:ggiMufUqsL5Do6Vz0ZuJuA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:fiUT8oGrRA==,iv:m5ncO9w71tHHvpkRq87EHOFwbxnilRzT1QDsNcMbH8U=,tag:Oo8k45yyW0IlKZoUE+VF6g==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:iquiBqQhA/bMvelf7/ZsY+aipGFCbw0s+DrRkx5lArsmsJwERZKLtvBKqg==,iv:v75oW3nUiobbw63cF32BHMGRRK9WaGeLK+kGQKbntTM=,tag:0mSQCTEtt9AzIRGfYJFDXA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:nYtSQY4i+hjNWLAsRBlJt6MwcAFEaGehPd50nRiE726lGU46v2HGDmeO4rCAqKgFYJA4HxF/4FwI5aZSY34GB8CEfYh8SYJrplGmUaqspIkQcL5IYd+J6Fjuty3qRZ2EWufp4RqKV/tCWy0JD2RTJ2GH9ToWKsNmtiuGRpL6a9bVgC51Kxs=,iv:ee9LTgWShNI+VG72n/yEnuT46tOJdPLzMEFb9DiTjYE=,tag:qHOozKRbt8se+W645zdSuQ==,type:str]
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBady9aZVJBL1phRSticFhr
            YUI5Yi9ZVW5wdGh1bnhrUWF3RDYrM1Q0eWxvCm5QemJVTEJDTHZEbVRET2RhSndR
            N0sxcTFYRkNFdTVoWG5xMmdsOHpDVW8KLS0tIGZvZ2t1N1E3STU5RHZLd1p0TkJp
            VjUzLzk2WkZWWWpLTksxbm9qNWd4YnMKBygaTMuBG7hLvRJK7nfVuyX9OGEMPoPZ
            oK7X28CG+pHWfUNcNUhZgeOoLDkZPzqQqyYU99VoJHjfO4V9hAEyNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T16:03:00Z"
    mac: ENC[AES256_GCM,data:fWf/q7SlTR3/yG0Z4pZJp59NYn/aDaG4XqYQtlkLABehnrRDWSXJcwwZBLliRPsOCXBq/i07gvgYgCf9ea6oXDoLsRcfGBEiqFDOLD4MV2ixxjBfECNqDnj8jlUDbYZmjybsyXz3gfe0vG89xePmQ1mRhAFjNRKRxmD9y70F6So=,iv:NcHy0GHeSTZrqZAbLTta9ZP8JW7Itq5M/fES91Y41lM=,tag:bH57dQ1QCOdAbI8lQtNtvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
