apiVersion: v1
data:
    apikey: ENC[AES256_GCM,data:PK9t2WsUO/4JGIiVo6upJaf0ZWrWeBkmFJSadx/Yu/2vTIsmUv0LvI6jScTVrKX2,iv:96dbbREANqZhQFtid8DhbPiuQi2kZTM9GRBXib3G7fQ=,tag:DTUCUtn6sbnqd4jlfKJcEA==,type:str]
kind: Secret
metadata:
    name: notifiarr-api-key
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWWIwa3ZQU3NGQStkUllv
            aXFMSWY1VzFDb2dtRWV1dnJoaU51OERCL1NrClR3VWNZU29sQ2xYVFZxeWo2NW01
            SVYrMytKRmJ6V0xxeC94WHN5azh3dHcKLS0tIDJkR0xZeThiK1B3ekZlYTBHWTlS
            cFdoTDBFRjVOTHI3WEFrUC9kRE5EanMKkrtoKkYDtPB6SVznE+/MZ3mhE5LWPEQv
            iFu1sdFLwe/ZBoiZHopHBa72kKOHQ3SaZX/Dao1Jyl9LjUWGvzw8Yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T20:05:16Z"
    mac: ENC[AES256_GCM,data:0HE8xecZ1UU4opNJIcd55SU6snjXXrW4lpuSBy3EvRfTepj6Pjhy4OcRg32pDvwTn0MvT6fTuPdA2i0hScYtHTxcKP+y+UhBEZlVxdIQgZRMmHCWcK3O3VevicCpOs5vCi3OydB62bNPZxmEH7vRYonA19EQYCySF76AC2KfvY4=,iv:58ik5rH3E0ZYT0hKCG6Vrxf6s9TEtqxAwPqEoI1JN1o=,tag:hPaXPPAHe5AGpQWbRlyulA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
