apiVersion: v1
data:
    AUTH_SECRET: ENC[AES256_GCM,data:4FyFtgORbTTtTBmxM0086tf3VashW15KRGYeBMLoEHO5dVm+HdlcWV2D4jtEL4gP3GkpuUzBEKiP0NWzv/JLzKaNQX2ZT6fpF2x0gwc+NvabI+g972hlZA==,iv:nxc8o7C2ospTO+gVEC5HbpCIcg2LD+PK+HffoiZstg4=,tag:CR4s5+wfgRPdMdMxBBazow==,type:str]
    PRINTER_TOKEN: ENC[AES256_GCM,data:zymgoui2pEajo3qk/n46iIiYj8c8eToPOlFu2gKRmjfCpa80EN0lsp8IV4XUj1sz+oTmiTCsO7QPe/0umx3KAg==,iv:vNyFGcozCyDnL13bAyutdSwBWQ5PSZd/D7gD27kpPOo=,tag:XE7tAnyvy01GJ2yxKWyhZQ==,type:str]
kind: Secret
metadata:
    name: reactive-resume-app-secret
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS1ZUVGlhSWxGcTRxU3lq
            alQzRERrQzVjUXZ1aENYd1daK0hRTm85NEd3CllTRGRlMVdJekx1ZVMxUDg4OVR2
            U3NlSURheFZQQ09adWhJdWpnZWt2OE0KLS0tIFF3TmlwNjB1Z3RJUkRxVGFLRGMw
            c081eEtwZTk4R0NCbmI5N2Y2SWh3VG8KkMG2KDou3zLY7bv3YjD/Cv/b0hesxRuw
            bLxoNf5O7AyV56QQ78DxHGgrDxuc7lARVlPVFCCpbg0yJEEv0IFdNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T10:11:23Z"
    mac: ENC[AES256_GCM,data:81jkJRWQd6xyrT9pmyB3zbAMBRP2ivoUqsPXUBJquskPYD2/oYnQTVoEsw/HfR1m0xK/DINzuUtVc9H1/D6gQVbgerMAGmB6KSbgMdu6ZLdAcQsNurKHR1Hv23W2ey4qvGCDqz98hnGCH0FcaZwMV8eSXnkdqCf4KJf45um435k=,iv:Q0dhsUOalbrTcaRe960/7oMg2s5sMhSpLuINeUkS/fU=,tag:Sl81+KRZ5CUym2Ukf/GMbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
