apiVersion: v1
data:
    DATABASE_URL: ENC[AES256_GCM,data:mfSt8ZaY73it6io79c2BUTyuc/NehXB7pG9evLqZyu/R63ueEgIRqCub9kh9Iaidkk1yOATaERLqYHVIyiKoO4vOok+9ue29dojVb91R4EWxCBIbHmFd8uNGdtL7ezyUtDnCtlozcfV+YklTnkbi0m+V3KdJswOWE9uZL1T2uBhXO7DIfB/KnGkbL0WTr1bu0o8Aq5Zjs00=,iv:vjXJidHaHo7FRkSsP2/LcA7wpTzZOge8360qWdYWIIs=,tag:vyQDrrhcVeAP49GGI8d2Eg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:98ZQ9ehQmfl++gyVJYCfG+/kbTGHAhYumZfS3PofNGFGMkSyr0gC3BkwSAajdJz50EFtjVID2SsaiSRX7nCRZg==,iv:R037rlUWdEcLed14bWfEo9KVqXZ6xci/hG9fbYuxG2Q=,tag:hWQch9wdd6EvOpUzcSA7ng==,type:str]
kind: Secret
metadata:
    name: reactive-resume-db-secret
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbTdSTllGWWVBTnE4cjRp
            ZmNRb1NlUUp0aUZCdDAxZzZLajYwejhqelVFCjZ5SFhrdWlmRmtMSk92bjNDczdz
            eE8yS0NiKytkVm1BNjErNFRwL2hFRk0KLS0tIFU1OG10cnNhWmJlcE9Hc0xBUGJ1
            NlE2b3lqZG9KUk54THAxV0xQeEd3d0UKY4PA0mVGU8i2L5RDQr9yDM7sikLwnRRo
            /rAp/ixdgO8CPiBd1TUYR5VSu0yw2cgy2OEQU8QmYYR0oNtVa+DvBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T10:11:23Z"
    mac: ENC[AES256_GCM,data:po0+bRQvAc9pWHBeP79GgC6viKzgA3d6RBHy//F2HMqi0Ez9LcVdgDBmuUc/+hhvkNGs3OKzms7B1vet9RFk7fScVYMLSDBEE8z9/lHzLppnkqYReGHkhjGxqmxF6WyqCjjljANPIQW2S6oG+mqY5bmEgzRBkXWrwxv9gysD/xM=,iv:Yy28EK7dHS9H0Fk6e9U670Ir/nwjQdl7GIh+wr2qZxI=,tag:fN9EtF4olllzkcN6MbCmrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
