apiVersion: v1
kind: Secret
metadata:
    name: romm-secret
    namespace: default
type: Opaque
stringData:
    DB_PASSWD: ENC[AES256_GCM,data:cf/biazstyq4Y7meUUg5BY1wx3bgu+Cweticsa8MY8TfqWP2pSXuLlJtPa8tUW3X4rYxQC4MlD9Oh1eleBTo1g==,iv:V022jhJDsFYWpzl02fMgtM7962XSFe9OzENksGxYbXs=,tag:woqvBy89sDBn5BOPKmTUSA==,type:str]
    ROMM_AUTH_SECRET_KEY: ENC[AES256_GCM,data:8FY+H+imtTWL2S1nIfflyaCwy0kV4d92tawXiDv7240S12+lEbEPrpIm/N2zTWth/G+93T3B/87J0dRt6c47Pg==,iv:jHnlNCt6CPrGzSOXblLXxLWv/yMsbp389/VtnQSSdoM=,tag:3eL1G2b/I/RVOOgXwoJp+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNmFhL0tjVjF6QXYycTcv
            N25yOEQxRFlxcFN3NHM1QzZOMFF5WEF2YVZ3CjdwMjVCQnBBSi9Yc2RMMDJCNlJ1
            ZlNOWTZRNzE0ZmRFR0hLODBXNDNaT2sKLS0tIGFTakY4d3JaR2hwb09wWVd6OE5a
            QldhQWRLOFBhaWlzS1ZqdFBValBOaG8K+iyYktwr20SlcHIyJ63dtcc+/fK20/wd
            p8ZDO/ibnYEnnRccYJMVXBoV07uQsTE612iT7ALZ1eEyMb4/IVAs6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T15:18:23Z"
    mac: ENC[AES256_GCM,data:haopwf07dw5F27hMtBKHyMbS0orxpxA6WRqYe27UdLrT80psTH/gHS3mr2h7wGMffldqYvD1RAAwGaq6Fhhg0fTVCzcrGXKOIy1KmOHxDdvgGXhQ1oH52SsIJWvwTgDk9B80FBtfKtSVIUarZ6I9q/5htLULWKTLPmM6xWLrP7M=,iv:bQWIASGiwuC0AbtYOyToUDg/FbuvCLM+LjRARZQ30iY=,tag:RMFN1Fvr2jve84NxzExJjA==,type:str]
    version: 3.13.3
