apiVersion: v1
data:
    APP_KEY: ENC[AES256_GCM,data:Sic8TGxC3jIiLl6SMCPaqH5JxAaE2hLYrnrOnK/Wdshpd0lQ4DMxbw/jD6Z6pMzny74h1AOtLBR9wAh+mfKtJBTuMvY=,iv:4FDYSMm/hcRgS0eLVmzIEIXOJHLaJW8ry3S2xk9Dqtg=,tag:Sbf2gfmKOYkPvrhQjHRhSw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:UotVcJQUdsfmNU0fZQqDI/VZMqzCvsugfZLb+qsMgeApQUUQyf6/7tW+LEe3zGvBZbCUEEbJ85Mphf2J,iv:mRUwm4zAmsu0amVpjpNbx9RPkv1p6VgAAD3ykIie0zo=,tag:qiokdgiWdu6zzsh4F/SmQg==,type:str]
kind: Secret
metadata:
    name: speedtest-tracker-secret
    namespace: default
type: Opaque
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TUMycWZyOHhTbWVkVUFW
            NDJiNmpzZlBuYm40UVQrSUFNVkNPOXA4eWo4ClpOUWdFdE5KTGgyY3FJdjJFNG53
            b3Z5cWNLZ1Q5ZllqRFRvUU5jVGJPSzQKLS0tIHgwT0FQbUZQN1dRakIvcjZ0cHZi
            Y1hEanlRV3dqT2NvVGdjTTMzaWNvcnMKts4cvOMy01ic6KnzU1xDfs7Sa5nt2FfT
            ZeshUBBGKuvKYrL0uPTaejIiphCfcmNfjHNi2XvpQJS2sGgwJxg6Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T08:13:43Z"
    mac: ENC[AES256_GCM,data:uZ2Ggmk7fWfoKnbrRuLEOLy0e7hAxbWhobvoQlbKz+n45STdjxxmiosHyuC9RVFtolrgC9t9uwM63Hz6J7yi3D8ojEOGi5WZY5zdAoFXA6Ccdw/8dtYMYkOiBGHyjqY8ANTqdvZeoPjB/YOyYNAvVxeEfE0wPz8pgYEBcVmoEmY=,iv:SgIj7rICoXBsQ97GZzVcrCtWvaWihSECF7CehTO26/4=,tag:ECyttfWK8YQES31QP5T6mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
