apiVersion: v1
kind: Secret
metadata:
    name: transmission-vpn-secret
    namespace: default
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:JJCQYN+W1K9vM09gFTvGGINDsZH+DjNgmJefuhsHxfTFb975wzg=,iv:zj3ILJjC/LC0Net6pyaLn6RvDEt+3UXBStFZTXAaXzI=,tag:rEovgDcZHHMehYUhO5Y1lw==,type:str]
    WIREGUARD_PRESHARED_KEY: ""
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcFZuQ3BNYURjQXBzQlpS
            K1VyS0VXTDVLdFE3RVQrcmhSaGdJQ1R3bHpVClp6Y2plbVoyMnhoWmh4WUZOZ3o4
            VHJyaDBQa2R1NDgzNk1lSE91YnNzcncKLS0tIGJQcWZEaHlCSWtYdjNidm5Kc3dZ
            a3N0T241QTFWSkZ3SWxQK01DTmZhbjQKAHz1mDRKpUndpXNPrnf7Czn0/wCbpS7f
            d6k8OQEcm3pZmQyF9Ugteg50xEcw/+m2+ShiW3Q+hMM6fzIyhX4NIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T12:03:06Z"
    mac: ENC[AES256_GCM,data:wBaT7ZF0qNWHN09CQ+DxBW+7cyQgerge9TdRIyfmdJsDO/TGxkpqaeLoSxF/UpzR9dUpkL5xQ2hOiDfsP7edFi2mc3hqR7ywC34EVG36sSj39CoCItpQT/z6Q4X6HsX/tolaTju9iOGbBZFYR8EUwMal1tNer/XwxTFDOFnJkOY=,iv:veyUn4l06ORKjDgRLTAJvPdZ6wB9GsFL2mDMEqY916U=,tag:qtgN5l0Mf/R1fnYxZ4kNKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
