apiVersion: v1
kind: Secret
metadata:
    name: transmission-gluetun-control-secret
    namespace: default
type: Opaque
stringData:
    GLUETUN_API_KEY: ENC[AES256_GCM,data:mAKCQhQkg74jpO0UKUNDBhcnyVR/Lw==,iv:71baereOYAaivVorqYKnv8izL3EGI2/htv+NhuQ6ugc=,tag:taCxT5UxToX8jEFy4W+ZBA==,type:str]
    HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: ENC[AES256_GCM,data:I6AIQKXpZuYJ3bLwuoIivJNo+wr3BAExUS5Y0/HvsIULHPXsG219/CZvCCLIvoTbl6K6,iv:htL9UJlnKnMEwywRfRbluMzbVP5HmWnJ2Gl3jVXKGrw=,tag:hjBhMsE5iMEiXxNT8E/xSw==,type:str]
sops:
    age:
        - recipient: age1hz8ustuz5mtmuc744xg7rllqew9z6yc99607fhuva3n79s7769sqj4jlkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VklCZDhFdmdpNTU5V2s1
            b3dOenZnU2V5K1F4L3lnQkxsYjhwT2hZQ1cwClpGMHdNM09Fa0prRC9hYUFXU203
            K2lDWS9Ob21LWEdYTFF5UW1VWVpyTVUKLS0tIHczSWhMVTJwT0o0RmEyTFlJQkhS
            U2FvMjlYelBJTDZ6NFJpbXZJMC9YV3MKeD6QKZv2HKQ80+UDXwZGKqOKNxMTLmqy
            Rx8lDXSls3cFxP9QJFu47V+2Km14o/+KV9DrpjV20lhQaa7KEsm7/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T14:38:01Z"
    mac: ENC[AES256_GCM,data:Qj3bSpDdEC2ql0i/hk7rttFG8nr1ETQVsC/wDdnVUCZrl4H3agUVtEMZoKBCxr3vrIKlVhUTcTgC6UDtVEpYQ3LClnoLYc3E91UHuk0OF3U+55fd8pB8hcAkHWGZxhED2q85HTxdyrNpP3LWQAtDfZq9xchg7QsTyQTdjdBumOw=,iv:L1DXcM158QhIVioJgC/3s27RvPZAcJyu6I+J9eBGz6k=,tag:lYhWekn6PtCpL7Dtar/cqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
