---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: fallenbagel/jellyseerr
              tag: latest
            env:
              TZ: "Asia/Singapore"
              LOG_LEVEL: "info"
            resources:
              requests:
                cpu: "75m"
                memory: "192Mi"
              limits:
                cpu: "500m"
                memory: "768Mi"

    service:
      main:
        ports:
          http:
            port: 5055

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: entertainment.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: jellyseerr
                  port: 5055

        annotations:
          external-dns.alpha.kubernetes.io/hostname: entertainment.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: jellyseerr-tls
            hosts:
              - entertainment.khzaw.dev

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /app/config
