# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/persistentvolumeclaim-v1.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-hdd-config
  resources:
    requests:
      storage: 20Gi
