# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/persistentvolumeclaim-v1.json
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-books-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 20Gi
