# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: default

spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false

  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-7nf-osf

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/advplyr/audiobookshelf
              tag: latest
            env:
              TZ: "Asia/Singapore"
            resources:
              requests:
                cpu: "75m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "1Gi"
    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: audiobookshelf.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: audiobookshelf
                  port: 80
        annotations:
          external-dns.alpha.kubernetes.io/hostname: audiobookshelf.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: audiobookshelf-tls
            hosts:
              - audiobookshelf.khzaw.dev

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: books
        globalMounts:
          - path: /audiobooks
          - path: /podcasts
          - path: /config
          - path: /metadata
