# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/rolebinding-rbac.authorization.k8s.io-v1.json
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resource-advisor
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: resource-advisor
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: resource-advisor
