---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-advisor
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
