# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/role-rbac.authorization.k8s.io-v1.json
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resource-advisor
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
