# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/serviceaccount-v1.json
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-advisor
  namespace: monitoring
