---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale # Install into the namespace created manually
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: tailscale-operator
      version: "1.82.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale-charts
        namespace: flux-system
  install:
    createNamespace: false
    remediation: { retries: 3 }
  upgrade:
    remediation: { retries: 3 }

  values:
    apiServerProxyConfig:
      mode: "false"
