---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tailscale
resources:
  - namespace.yaml
  - helmrelease.yaml
  - rbac-patch-clusterrole.yaml
  - rbac-patch-clusterrolebinding.yaml
