# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/clusterrolebinding-rbac.authorization.k8s.io-v1.json
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-operator-endpointslice-reader-binding
subjects:
  - kind: ServiceAccount
    name: tailscale-operator # The SA created by the Helm chart
    namespace: tailscale    # Namespace where the SA lives
roleRef:
  kind: ClusterRole
  name: tailscale-operator-endpointslice-reader # The ClusterRole created above
  apiGroup: rbac.authorization.k8s.io
