
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellystat
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: cyfershepard/jellystat
              tag: latest
            command:
              - sh
              - -c
            args:
              - |
                echo "Waiting for PostgreSQL..."
                for i in $(seq 1 60); do
                  if nc -z 127.0.0.1 5432 2>/dev/null; then
                    echo "PostgreSQL is ready!"
                    break
                  fi
                  echo "Attempt $i/60..."
                  sleep 2
                done
                exec npm start
            env:
              - name: POSTGRES_USER
                value: "jellystat"
              - name: POSTGRES_PASSWORD
                valueFrom: &db_password_ref
                  secretKeyRef:
                    name: jellystat-db-secret
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_IP
                value: "127.0.0.1"
              - name: POSTGRES_PORT
                value: "5432"
              - name: POSTGRES_DB
                value: "jellystat"
              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: jellystat-app-secret
                    key: JWT_SECRET
              - name: TZ
                value: "Asia/Singapore"
          db:
            image:
              repository: postgres
              tag: 16-alpine
            env:
              - name: POSTGRES_USER
                value: "jellystat"
              - name: POSTGRES_DB
                value: "jellystat"
              - name: POSTGRES_PASSWORD
                valueFrom: *db_password_ref
              - name: PGDATA
                value: "/var/lib/postgresql/data/pgdata" # Subpath prevents permission issue

    service:
      main:
        controller: main
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: jellystat.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: jellystat
                  port: 3000
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-prod

        tls:
          - secretName: jellystat-tls
            hosts:
              - jellystat.khzaw.dev

    persistence:
      db-data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 5Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          main:
            db: # Container Name
              - path: /var/lib/postgresql/data
