# yaml-language-server: $schema=https://raw.githubusercontent.com/community-charts/helm-charts/main/charts/actualbudget/values.schema.json
---
image:
  repository: actualbudget/actual-server
  pullPolicy: Always
  tag: "26.3.0"

service:
  type: ClusterIP
  port: 5006

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 6

nodeSelector:
  kubernetes.io/hostname: ${PRIMARY_NODE_NAME}

podSecurityContext:
  fsGroup: null
  fsGroupChangePolicy: null

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: actual.${BASE_DOMAIN}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: actual.${BASE_DOMAIN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: actual-tls
      hosts:
        - actual.${BASE_DOMAIN}

persistence:
  enabled: true
  storageClass: truenas-nfs
  size: 2Gi
  accessModes:
    - ReadWriteOnce

strategy:
  type: Recreate
