# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tracerr
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/connorgallopo/tracearr
              tag: latest
            env:
              # Required:
              # - tracerr-app-secret (JWT_SECRET, COOKIE_SECRET)
              # - tracerr-db-secret (POSTGRES_PASSWORD, DATABASE_URL)
              - name: TZ
                value: "Asia/Singapore"
              - name: NODE_ENV
                value: production
              - name: HOST
                value: 0.0.0.0
              - name: PORT
                value: "3000"
              - name: CORS_ORIGIN
                value: "*"
              - name: LOG_LEVEL
                value: info
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: tracerr-db-secret
                    key: DATABASE_URL
              - name: REDIS_URL
                value: redis://127.0.0.1:6379
              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: tracerr-app-secret
                    key: JWT_SECRET
              - name: COOKIE_SECRET
                valueFrom:
                  secretKeyRef:
                    name: tracerr-app-secret
                    key: COOKIE_SECRET
            resources:
              requests:
                cpu: "200m"
                memory: "512Mi"
              limits:
                cpu: "800m"
                memory: "1536Mi"
            probes:
              liveness:
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 30
                  periodSeconds: 20
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6

          db:
            image:
              repository: timescale/timescaledb
              tag: 2.25.0-pg16
            command:
              - postgres
              - -c
              - timescaledb.max_tuples_decompressed_per_dml_transaction=0
              - -c
              - timescaledb.max_tuples_decompressed_per_compression=0
              - -c
              - timescaledb.telemetry_level=off
            env:
              - name: POSTGRES_USER
                value: tracearr
              - name: POSTGRES_DB
                value: tracearr
              - name: POSTGRES_PASSWORD
                valueFrom: &tracerr_db_password_ref
                  secretKeyRef:
                    name: tracerr-db-secret
                    key: POSTGRES_PASSWORD
              - name: PGDATA
                value: "/var/lib/postgresql/data/pgdata" # Subpath prevents permission issue
            resources:
              requests:
                cpu: "200m"
                memory: "768Mi"
              limits:
                cpu: "1500m"
                memory: "2Gi"
            probes:
              readiness:
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - pg_isready -U tracearr -d tracearr
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 12
              liveness:
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - pg_isready -U tracearr -d tracearr
                  initialDelaySeconds: 30
                  periodSeconds: 20
                  timeoutSeconds: 5
                  failureThreshold: 6

          redis:
            image:
              repository: redis
              tag: 8-alpine
            command:
              - redis-server
              - --appendonly
              - "yes"
            resources:
              requests:
                cpu: "25m"
                memory: "64Mi"
              limits:
                cpu: "300m"
                memory: "256Mi"
            probes:
              readiness:
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - redis-cli ping | grep -q PONG
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 12
              liveness:
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - redis-cli ping | grep -q PONG
                  initialDelaySeconds: 20
                  periodSeconds: 20
                  timeoutSeconds: 3
                  failureThreshold: 6

    service:
      main:
        controller: main
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: tracerr.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/hostname: tracerr.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: tracerr-tls
            hosts:
              - tracerr.khzaw.dev

    persistence:
      # Postgres/Timescale data should stay node-local to avoid NFS latency/fsync semantics issues.
      # This mirrors the existing "DB on local-path" convention used elsewhere in this repo (e.g. Immich/Jellystat).
      db-data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: local-path
        size: 10Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          main:
            db:
              - path: /var/lib/postgresql/data

      redis-data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        size: 1Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          main:
            redis:
              - path: /data
