# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tracerr
  namespace: default
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install: { remediation: { retries: 3 } }
  upgrade: { remediation: { retries: 3 } }
  values:
    defaultPodOptionsStrategy: merge
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: talos-7nf-osf

    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/connorgallopo/tracearr
              # Pin to a known-good release; avoid surprise breakage from :latest.
              tag: 1.4.18
            env:
              # Required:
              # - tracerr-app-secret (JWT_SECRET, COOKIE_SECRET)
              # - tracerr-db-secret (POSTGRES_PASSWORD, DATABASE_URL)
              - name: TZ
                value: "Asia/Singapore"
              - name: NODE_ENV
                value: production
              - name: HOST
                value: 0.0.0.0
              - name: PORT
                value: "3000"
              - name: CORS_ORIGIN
                value: "*"
              - name: LOG_LEVEL
                value: info
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: tracerr-db-secret
                    key: DATABASE_URL
              - name: REDIS_URL
                value: redis://127.0.0.1:6379
              - name: JWT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: tracerr-app-secret
                    key: JWT_SECRET
              - name: COOKIE_SECRET
                valueFrom:
                  secretKeyRef:
                    name: tracerr-app-secret
                    key: COOKIE_SECRET
            resources:
              requests:
                cpu: "200m"
                memory: "512Mi"
              limits:
                cpu: "800m"
                memory: "1536Mi"
            probes:
              startup:
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 30
              liveness:
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  periodSeconds: 20
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6

          redis:
            image:
              repository: redis
              tag: 8-alpine
            command:
              - redis-server
              - --appendonly
              - "yes"
            resources:
              requests:
                cpu: "25m"
                memory: "64Mi"
              limits:
                cpu: "300m"
                memory: "256Mi"
            probes:
              readiness:
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - redis-cli ping | grep -q PONG
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 12
              liveness:
                spec:
                  exec:
                    command:
                      - sh
                      - -c
                      - redis-cli ping | grep -q PONG
                  initialDelaySeconds: 20
                  periodSeconds: 20
                  timeoutSeconds: 3
                  failureThreshold: 6

    service:
      main:
        controller: main
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: tracerr.khzaw.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        annotations:
          external-dns.alpha.kubernetes.io/hostname: tracerr.khzaw.dev
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: tracerr-tls
            hosts:
              - tracerr.khzaw.dev

    persistence:
      redis-data:
        enabled: true
        type: persistentVolumeClaim
        storageClass: truenas-nfs
        size: 1Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          main:
            redis:
              - path: /data
