---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helmrelease.yaml
  - ingress.yaml
configMapGenerator:
  - name: calibre-helm-values
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
