# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.0-standalone-strict/service-v1.json
---
apiVersion: v1
kind: Service
metadata:
  name: blog-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: blog.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: mmcal-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mmcal.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: rangoonmapper-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: rangoonmapper.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-speedtest-cname
  namespace: public-edge
  annotations:
    # Create DNS alias to Cloudflare Tunnel edge endpoint.
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}speedtest.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-chartsdb-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}chartsdb.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-booklore-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}booklore.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-shelfmark-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}shelfmark.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-jellyfin-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}jellyfin.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-seerr-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}seerr.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-audiobookshelf-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}audiobookshelf.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-uptime-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}uptime.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-sonarr-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}sonarr.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-radarr-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}radarr.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-tracerr-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}tracerr.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-tunarr-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}tunarr.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-vaultwarden-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}vaultwarden.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-immich-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}immich.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-calibre-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}calibre.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
---
apiVersion: v1
kind: Service
metadata:
  name: share-calibre-manage-cname
  namespace: public-edge
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${SHARE_HOST_PREFIX}calibre-manage.${BASE_DOMAIN}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  type: ExternalName
  externalName: a0a36100-5576-4d6c-b8c8-6c1441b03774.cfargotunnel.com
